build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
labels:
  maintainer: "yourname@example.com"
  org.opencontainers.image.title: "PaddleOCR Add-on"
  org.opencontainers.image.description: "Lokaler PaddleOCR-Service für Home Assistant"
args:
  BUILD_FROM: "ghcr.io/home-assistant/amd64-base:3.19"
