name: "Receipt OCR Add-on"
version: "1.1.4"
slug: "receipt_ocr_addon"
description: "Lokaler OCR-Service, der Bilder verarbeitet und Ergebnisse in /share/ocr/results.json speichert."
arch:
  - aarch64
  - amd64
startup: services
boot: auto
options:
  host: "0.0.0.0"
  port: 5000
schema:
  host: str?
  port: port?
build: .  
ingress: true
ingress_port: 5000
ports:
  5000/tcp: 5000
panel_icon: mdi:file-upload
panel_title: Receipt OCR
map:
  - share:rw
  - media:rw



