name: "Receipt OCR Add-on"
version: "1.1.1"
slug: "receipt_ocr_addon"
description: "Lokaler OCR-Service, der Bilder verarbeitet und Ergebnisse in /share/ocr/results.json speichert."
arch:
  - aarch64
  - amd64
startup: services
boot: auto
options: {}
schema: {}
ingress: true
ingress_port: 0
panel_icon: mdi:file-upload
panel_title: Receipt OCR
map:
  - share:rw
  - media:rw
webui: "[PROTO:ingress]://[HOST]/api/hassio_ingress/[SLUG]/"
