name: "Receipt OCR Add-on"
version: "1.0.7"
slug: "receipt_ocr_addon"
description: "Lokaler OCR-Service, der Bilder verarbeitet und Ergebnisse in /share/ocr/result.yaml speichert."
arch:
  - aarch64
  - amd64
startup: services
boot: auto
options: {}
schema: {}
ports:
  5000/tcp: 5000
map:
  - share:rw
  - media:rw
webui: "http://[HOST]:[PORT:5000]"
